version: '3'

volumes:
  mysqlData:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysqlData:/var/lib/mysql
  mongo:
    image: mongo:4.2
    container_name: mongo
    ports:
      - "27017:27017"
  jenkins:
    image: jenkins/jenkins:2.222.4-lts
    container_name: jenkins
    ports:
      - "8080:8080"